spring:
  datasource:
    url: jdbc:h2:mem:task-tracker
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

rsa:
  private-key: classpath:certificates/private.pem
  public-key: classpath:certificates/public.pem
